-- 004_nz_locations.sql
-- Nationwide locality list. Adds every town/suburb outside the original
-- Christchurch seed so people can create an account anywhere in NZ.
-- Safe to re-run: unique (name, region) plus on conflict do nothing.
-- Note names repeat across regions (four Richmonds, two Bishopdales) - that is
-- why lookups resolve by id, not by name.

insert into suburbs (name, region, territorial_authority) values
  ('Addington','Canterbury','Christchurch'),
  ('Aidanfield','Canterbury','Christchurch'),
  ('Aranui','Canterbury','Christchurch'),
  ('Avonhead','Canterbury','Christchurch'),
  ('Avonside','Canterbury','Christchurch'),
  ('Barrington','Canterbury','Christchurch'),
  ('Beckenham','Canterbury','Christchurch'),
  ('Belfast','Canterbury','Christchurch'),
  ('Bexley','Canterbury','Christchurch'),
  ('Bishopdale','Canterbury','Christchurch'),
  ('Bromley','Canterbury','Christchurch'),
  ('Brooklands','Canterbury','Christchurch'),
  ('Bryndwr','Canterbury','Christchurch'),
  ('Burnside','Canterbury','Christchurch'),
  ('Burwood','Canterbury','Christchurch'),
  ('Casebrook','Canterbury','Christchurch'),
  ('Cashmere','Canterbury','Christchurch'),
  ('Clifton','Canterbury','Christchurch'),
  ('Cracroft','Canterbury','Christchurch'),
  ('Cust','Canterbury','Christchurch'),
  ('Dallington','Canterbury','Christchurch'),
  ('Darfield','Canterbury','Christchurch'),
  ('Diamond Harbour','Canterbury','Christchurch'),
  ('Edgeware','Canterbury','Christchurch'),
  ('Fendalton','Canterbury','Christchurch'),
  ('Ferrymead','Canterbury','Christchurch'),
  ('Governors Bay','Canterbury','Christchurch'),
  ('Halswell','Canterbury','Christchurch'),
  ('Harewood','Canterbury','Christchurch'),
  ('Heathcote Valley','Canterbury','Christchurch'),
  ('Hei Hei','Canterbury','Christchurch'),
  ('Hillmorton','Canterbury','Christchurch'),
  ('Hoon Hay','Canterbury','Christchurch'),
  ('Hornby','Canterbury','Christchurch'),
  ('Huntsbury','Canterbury','Christchurch'),
  ('Ilam','Canterbury','Christchurch'),
  ('Islington','Canterbury','Christchurch'),
  ('Kaiapoi','Canterbury','Christchurch'),
  ('Leeston','Canterbury','Christchurch'),
  ('Lincoln','Canterbury','Christchurch'),
  ('Linwood','Canterbury','Christchurch'),
  ('Lyttelton','Canterbury','Christchurch'),
  ('Mairehau','Canterbury','Christchurch'),
  ('Marshland','Canterbury','Christchurch'),
  ('Merivale','Canterbury','Christchurch'),
  ('Middleton','Canterbury','Christchurch'),
  ('Mount Pleasant','Canterbury','Christchurch'),
  ('New Brighton','Canterbury','Christchurch'),
  ('North New Brighton','Canterbury','Christchurch'),
  ('Northwood','Canterbury','Christchurch'),
  ('Ohoka','Canterbury','Christchurch'),
  ('Opawa','Canterbury','Christchurch'),
  ('Oxford','Canterbury','Christchurch'),
  ('Papanui','Canterbury','Christchurch'),
  ('Parklands','Canterbury','Christchurch'),
  ('Pegasus','Canterbury','Christchurch'),
  ('Phillipstown','Canterbury','Christchurch'),
  ('Prebbleton','Canterbury','Christchurch'),
  ('Prestons','Canterbury','Christchurch'),
  ('Rangiora','Canterbury','Christchurch'),
  ('Redcliffs','Canterbury','Christchurch'),
  ('Redwood','Canterbury','Christchurch'),
  ('Riccarton','Canterbury','Christchurch'),
  ('Richmond','Canterbury','Christchurch'),
  ('Rolleston','Canterbury','Christchurch'),
  ('Russley','Canterbury','Christchurch'),
  ('Shirley','Canterbury','Christchurch'),
  ('Sockburn','Canterbury','Christchurch'),
  ('Somerfield','Canterbury','Christchurch'),
  ('South New Brighton','Canterbury','Christchurch'),
  ('Spreydon','Canterbury','Christchurch'),
  ('Springston','Canterbury','Christchurch'),
  ('St Albans','Canterbury','Christchurch'),
  ('St Martins','Canterbury','Christchurch'),
  ('Strowan','Canterbury','Christchurch'),
  ('Sumner','Canterbury','Christchurch'),
  ('Swannanoa','Canterbury','Christchurch'),
  ('Sydenham','Canterbury','Christchurch'),
  ('Tai Tapu','Canterbury','Christchurch'),
  ('Templeton','Canterbury','Christchurch'),
  ('Upper Riccarton','Canterbury','Christchurch'),
  ('Waimairi Beach','Canterbury','Christchurch'),
  ('Wainoni','Canterbury','Christchurch'),
  ('Waltham','Canterbury','Christchurch'),
  ('West Melton','Canterbury','Christchurch'),
  ('Westmorland','Canterbury','Christchurch'),
  ('Wigram','Canterbury','Christchurch'),
  ('Woodend','Canterbury','Christchurch'),
  ('Woolston','Canterbury','Christchurch'),
  ('Yaldhurst','Canterbury','Christchurch'),
  ('Kaikoura','Canterbury','Kaikoura'),
  ('Clarence','Canterbury','Clarence'),
  ('Kekerengu','Canterbury','Kekerengu'),
  ('Hapuku','Canterbury','Hapuku'),
  ('Peketa','Canterbury','Peketa'),
  ('Goose Bay','Canterbury','Goose Bay'),
  ('Oaro','Canterbury','Oaro'),
  ('Mt Lyford','Canterbury','Mt Lyford'),
  ('Parnassus','Canterbury','Parnassus'),
  ('Cheviot','Canterbury','Cheviot'),
  ('Gore Bay','Canterbury','Gore Bay'),
  ('Domett','Canterbury','Domett'),
  ('Greta Valley','Canterbury','Greta Valley'),
  ('Motunau Beach','Canterbury','Motunau Beach'),
  ('Scargill','Canterbury','Scargill'),
  ('Waiau','Canterbury','Waiau'),
  ('Rotherham','Canterbury','Rotherham'),
  ('Culverden','Canterbury','Culverden'),
  ('Hanmer Springs','Canterbury','Hanmer Springs'),
  ('Hawarden','Canterbury','Hawarden'),
  ('Waikari','Canterbury','Waikari'),
  ('Omihi','Canterbury','Omihi'),
  ('Waipara','Canterbury','Waipara'),
  ('Amberley','Canterbury','Amberley'),
  ('Leithfield','Canterbury','Leithfield'),
  ('Leithfield Beach','Canterbury','Leithfield Beach'),
  ('Sefton','Canterbury','Sefton'),
  ('Ashley','Canterbury','Ashley'),
  ('Loburn','Canterbury','Loburn'),
  ('Tuahiwi','Canterbury','Tuahiwi'),
  ('Clarkville','Canterbury','Clarkville'),
  ('Kairaki','Canterbury','Kairaki'),
  ('The Pines Beach','Canterbury','The Pines Beach'),
  ('Woodend Beach','Canterbury','Woodend Beach'),
  ('Ravenswood','Canterbury','Ravenswood'),
  ('Waikuku','Canterbury','Waikuku'),
  ('Waikuku Beach','Canterbury','Waikuku Beach'),
  ('Fernside','Canterbury','Fernside'),
  ('View Hill','Canterbury','View Hill'),
  ('West Eyreton','Canterbury','West Eyreton'),
  ('Eyrewell','Canterbury','Eyrewell'),
  ('Weedons','Canterbury','Weedons'),
  ('Burnham','Canterbury','Burnham'),
  ('Ladbrooks','Canterbury','Ladbrooks'),
  ('Motukarara','Canterbury','Motukarara'),
  ('Greenpark','Canterbury','Greenpark'),
  ('Doyleston','Canterbury','Doyleston'),
  ('Southbridge','Canterbury','Southbridge'),
  ('Dunsandel','Canterbury','Dunsandel'),
  ('Selwyn Huts','Canterbury','Selwyn Huts'),
  ('Kirwee','Canterbury','Kirwee'),
  ('Charing Cross','Canterbury','Charing Cross'),
  ('Aylesbury','Canterbury','Aylesbury'),
  ('Sheffield','Canterbury','Sheffield'),
  ('Waddington','Canterbury','Waddington'),
  ('Springfield','Canterbury','Springfield'),
  ('Castle Hill','Canterbury','Castle Hill'),
  ('Arthurs Pass','Canterbury','Arthurs Pass'),
  ('Coalgate','Canterbury','Coalgate'),
  ('Glentunnel','Canterbury','Glentunnel'),
  ('Whitecliffs','Canterbury','Whitecliffs'),
  ('Hororata','Canterbury','Hororata'),
  ('Windwhistle','Canterbury','Windwhistle'),
  ('Lake Coleridge','Canterbury','Lake Coleridge'),
  ('Little River','Canterbury','Little River'),
  ('Birdlings Flat','Canterbury','Birdlings Flat'),
  ('Akaroa','Canterbury','Akaroa'),
  ('Duvauchelle','Canterbury','Duvauchelle'),
  ('Takamatua','Canterbury','Takamatua'),
  ('Barrys Bay','Canterbury','Barrys Bay'),
  ('Wainui','Canterbury','Wainui'),
  ('Okains Bay','Canterbury','Okains Bay'),
  ('Le Bons Bay','Canterbury','Le Bons Bay'),
  ('Little Akaloa','Canterbury','Little Akaloa'),
  ('Pigeon Bay','Canterbury','Pigeon Bay'),
  ('Port Levy','Canterbury','Port Levy'),
  ('Rakaia','Canterbury','Rakaia'),
  ('Rakaia Huts','Canterbury','Rakaia Huts'),
  ('Barrhill','Canterbury','Barrhill'),
  ('Methven','Canterbury','Methven'),
  ('Mount Somers','Canterbury','Mount Somers'),
  ('Staveley','Canterbury','Staveley'),
  ('Springburn','Canterbury','Springburn'),
  ('Mayfield','Canterbury','Mayfield'),
  ('Ashburton','Canterbury','Ashburton'),
  ('Allenton','Canterbury','Ashburton'),
  ('Hampstead','Canterbury','Ashburton'),
  ('Netherby','Canterbury','Ashburton'),
  ('Tinwald','Canterbury','Ashburton'),
  ('Fairton','Canterbury','Fairton'),
  ('Winslow','Canterbury','Winslow'),
  ('Dromore','Canterbury','Dromore'),
  ('Chertsey','Canterbury','Chertsey'),
  ('Lauriston','Canterbury','Lauriston'),
  ('Willowby','Canterbury','Willowby'),
  ('Wakanui','Canterbury','Wakanui'),
  ('Seafield','Canterbury','Seafield'),
  ('Longbeach','Canterbury','Longbeach'),
  ('Hinds','Canterbury','Hinds'),
  ('Ealing','Canterbury','Ealing'),
  ('Lowcliffe','Canterbury','Lowcliffe'),
  ('Rangitata','Canterbury','Rangitata'),
  ('Orari','Canterbury','Orari'),
  ('Arundel','Canterbury','Arundel'),
  ('Geraldine','Canterbury','Geraldine'),
  ('Woodbury','Canterbury','Woodbury'),
  ('Peel Forest','Canterbury','Peel Forest'),
  ('Winchester','Canterbury','Winchester'),
  ('Temuka','Canterbury','Temuka'),
  ('Clandeboye','Canterbury','Clandeboye'),
  ('Pleasant Point','Canterbury','Pleasant Point'),
  ('Cave','Canterbury','Cave'),
  ('Timaru','Canterbury','Timaru'),
  ('Fairview','Canterbury','Timaru'),
  ('Gleniti','Canterbury','Timaru'),
  ('Glenwood','Canterbury','Timaru'),
  ('Highfield','Canterbury','Timaru'),
  ('Maori Hill','Canterbury','Timaru'),
  ('Marchwiel','Canterbury','Timaru'),
  ('Parkside','Canterbury','Timaru'),
  ('Redruth','Canterbury','Timaru'),
  ('Seaview','Canterbury','Timaru'),
  ('Waimataitai','Canterbury','Timaru'),
  ('Washdyke','Canterbury','Timaru'),
  ('Watlington','Canterbury','Timaru'),
  ('West End','Canterbury','Timaru'),
  ('Seadown','Canterbury','Seadown'),
  ('Levels','Canterbury','Levels'),
  ('Pareora','Canterbury','Pareora'),
  ('St Andrews','Canterbury','St Andrews'),
  ('Makikihi','Canterbury','Makikihi'),
  ('Albury','Canterbury','Albury'),
  ('Fairlie','Canterbury','Fairlie'),
  ('Kimbell','Canterbury','Kimbell'),
  ('Burkes Pass','Canterbury','Burkes Pass'),
  ('Tekapo','Canterbury','Tekapo'),
  ('Twizel','Canterbury','Twizel'),
  ('Mount Cook Village','Canterbury','Mount Cook Village'),
  ('Waimate','Canterbury','Waimate'),
  ('Hook','Canterbury','Hook'),
  ('Studholme','Canterbury','Studholme'),
  ('Morven','Canterbury','Morven'),
  ('Glenavy','Canterbury','Glenavy'),
  ('Albany','Auckland','Auckland'),
  ('Avondale','Auckland','Auckland'),
  ('Balmoral','Auckland','Auckland'),
  ('Beach Haven','Auckland','Auckland'),
  ('Birkenhead','Auckland','Auckland'),
  ('Blockhouse Bay','Auckland','Auckland'),
  ('Botany Downs','Auckland','Auckland'),
  ('Browns Bay','Auckland','Auckland'),
  ('Bucklands Beach','Auckland','Auckland'),
  ('Clendon Park','Auckland','Auckland'),
  ('Clevedon','Auckland','Auckland'),
  ('Cockle Bay','Auckland','Auckland'),
  ('Dannemora','Auckland','Auckland'),
  ('Devonport','Auckland','Auckland'),
  ('Drury','Auckland','Auckland'),
  ('East Tamaki','Auckland','Auckland'),
  ('Eden Terrace','Auckland','Auckland'),
  ('Ellerslie','Auckland','Auckland'),
  ('Epsom','Auckland','Auckland'),
  ('Favona','Auckland','Auckland'),
  ('Flat Bush','Auckland','Auckland'),
  ('Forrest Hill','Auckland','Auckland'),
  ('Freemans Bay','Auckland','Auckland'),
  ('Glen Eden','Auckland','Auckland'),
  ('Glen Innes','Auckland','Auckland'),
  ('Glendene','Auckland','Auckland'),
  ('Glendowie','Auckland','Auckland'),
  ('Glenfield','Auckland','Auckland'),
  ('Grafton','Auckland','Auckland'),
  ('Greenlane','Auckland','Auckland'),
  ('Grey Lynn','Auckland','Auckland'),
  ('Half Moon Bay','Auckland','Auckland'),
  ('Henderson','Auckland','Auckland'),
  ('Herne Bay','Auckland','Auckland'),
  ('Hillsborough','Auckland','Auckland'),
  ('Hobsonville','Auckland','Auckland'),
  ('Howick','Auckland','Auckland'),
  ('Huapai','Auckland','Auckland'),
  ('Kelston','Auckland','Auckland'),
  ('Kingsland','Auckland','Auckland'),
  ('Kohimarama','Auckland','Auckland'),
  ('Kumeu','Auckland','Auckland'),
  ('Lynfield','Auckland','Auckland'),
  ('Mairangi Bay','Auckland','Auckland'),
  ('Mangere','Auckland','Auckland'),
  ('Mangere Bridge','Auckland','Auckland'),
  ('Mangere East','Auckland','Auckland'),
  ('Manukau','Auckland','Auckland'),
  ('Manurewa','Auckland','Auckland'),
  ('Massey','Auckland','Auckland'),
  ('Meadowbank','Auckland','Auckland'),
  ('Mellons Bay','Auckland','Auckland'),
  ('Milford','Auckland','Auckland'),
  ('Millwater','Auckland','Auckland'),
  ('Mission Bay','Auckland','Auckland'),
  ('Morningside','Auckland','Auckland'),
  ('Mount Albert','Auckland','Auckland'),
  ('Mount Eden','Auckland','Auckland'),
  ('Mount Roskill','Auckland','Auckland'),
  ('Mount Wellington','Auckland','Auckland'),
  ('Murrays Bay','Auckland','Auckland'),
  ('Narrow Neck','Auckland','Auckland'),
  ('New Lynn','Auckland','Auckland'),
  ('New Windsor','Auckland','Auckland'),
  ('Newmarket','Auckland','Auckland'),
  ('Newton','Auckland','Auckland'),
  ('Northcote','Auckland','Auckland'),
  ('Northcross','Auckland','Auckland'),
  ('Onehunga','Auckland','Auckland'),
  ('Orewa','Auckland','Auckland'),
  ('Otahuhu','Auckland','Auckland'),
  ('Otara','Auckland','Auckland'),
  ('Oteha','Auckland','Auckland'),
  ('Pahurehure','Auckland','Auckland'),
  ('Pakuranga','Auckland','Auckland'),
  ('Panmure','Auckland','Auckland'),
  ('Papakura','Auckland','Auckland'),
  ('Papatoetoe','Auckland','Auckland'),
  ('Parnell','Auckland','Auckland'),
  ('Penrose','Auckland','Auckland'),
  ('Pinehill','Auckland','Auckland'),
  ('Point Chevalier','Auckland','Auckland'),
  ('Ponsonby','Auckland','Auckland'),
  ('Pukekohe','Auckland','Auckland'),
  ('Ranui','Auckland','Auckland'),
  ('Remuera','Auckland','Auckland'),
  ('Rosedale','Auckland','Auckland'),
  ('Rothesay Bay','Auckland','Auckland'),
  ('Royal Oak','Auckland','Auckland'),
  ('Sandringham','Auckland','Auckland'),
  ('Silverdale','Auckland','Auckland'),
  ('Snells Beach','Auckland','Auckland'),
  ('St Heliers','Auckland','Auckland'),
  ('St Johns','Auckland','Auckland'),
  ('St Lukes','Auckland','Auckland'),
  ('Stanmore Bay','Auckland','Auckland'),
  ('Stonefields','Auckland','Auckland'),
  ('Sunnynook','Auckland','Auckland'),
  ('Sunnyvale','Auckland','Auckland'),
  ('Swanson','Auckland','Auckland'),
  ('Takapuna','Auckland','Auckland'),
  ('Te Atatu Peninsula','Auckland','Auckland'),
  ('Te Atatu South','Auckland','Auckland'),
  ('Three Kings','Auckland','Auckland'),
  ('Titirangi','Auckland','Auckland'),
  ('Torbay','Auckland','Auckland'),
  ('Totara Heights','Auckland','Auckland'),
  ('Unsworth Heights','Auckland','Auckland'),
  ('Waitakere','Auckland','Auckland'),
  ('Waiuku','Auckland','Auckland'),
  ('Wattle Downs','Auckland','Auckland'),
  ('Wellsford','Auckland','Auckland'),
  ('West Harbour','Auckland','Auckland'),
  ('Western Springs','Auckland','Auckland'),
  ('Westgate','Auckland','Auckland'),
  ('Westmere','Auckland','Auckland'),
  ('Whangaparaoa','Auckland','Auckland'),
  ('Whenuapai','Auckland','Auckland'),
  ('Windsor Park','Auckland','Auckland'),
  ('Wiri','Auckland','Auckland'),
  ('Warkworth','Auckland','Warkworth'),
  ('Algies Bay','Auckland','Algies Bay'),
  ('Sandspit','Auckland','Sandspit'),
  ('Matakana','Auckland','Matakana'),
  ('Point Wells','Auckland','Point Wells'),
  ('Omaha','Auckland','Omaha'),
  ('Leigh','Auckland','Leigh'),
  ('Pakiri','Auckland','Pakiri'),
  ('Kaipara Flats','Auckland','Kaipara Flats'),
  ('Te Hana','Auckland','Te Hana'),
  ('Tomarata','Auckland','Tomarata'),
  ('Puhoi','Auckland','Puhoi'),
  ('Waiwera','Auckland','Waiwera'),
  ('Hatfields Beach','Auckland','Hatfields Beach'),
  ('Kaukapakapa','Auckland','Kaukapakapa'),
  ('Waitoki','Auckland','Waitoki'),
  ('Wainui','Auckland','Wainui'),
  ('Dairy Flat','Auckland','Dairy Flat'),
  ('Coatesville','Auckland','Coatesville'),
  ('Helensville','Auckland','Helensville'),
  ('Parakai','Auckland','Parakai'),
  ('South Head','Auckland','South Head'),
  ('Shelly Beach','Auckland','Shelly Beach'),
  ('Riverhead','Auckland','Riverhead'),
  ('Waimauku','Auckland','Waimauku'),
  ('Muriwai','Auckland','Muriwai'),
  ('Bethells Beach','Auckland','Bethells Beach'),
  ('Piha','Auckland','Piha'),
  ('Karekare','Auckland','Karekare'),
  ('Huia','Auckland','Huia'),
  ('Cornwallis','Auckland','Cornwallis'),
  ('Oratia','Auckland','Oratia'),
  ('Henderson Valley','Auckland','Henderson Valley'),
  ('Whitford','Auckland','Whitford'),
  ('Brookby','Auckland','Brookby'),
  ('Beachlands','Auckland','Beachlands'),
  ('Maraetai','Auckland','Maraetai'),
  ('Kawakawa Bay','Auckland','Kawakawa Bay'),
  ('Orere Point','Auckland','Orere Point'),
  ('Ardmore','Auckland','Ardmore'),
  ('Karaka','Auckland','Karaka'),
  ('Kingseat','Auckland','Kingseat'),
  ('Waiau Pa','Auckland','Waiau Pa'),
  ('Clarks Beach','Auckland','Clarks Beach'),
  ('Glenbrook','Auckland','Glenbrook'),
  ('Awhitu','Auckland','Awhitu'),
  ('Matakawau','Auckland','Matakawau'),
  ('Buckland','Auckland','Buckland'),
  ('Paerata','Auckland','Paerata'),
  ('Patumahoe','Auckland','Patumahoe'),
  ('Ramarama','Auckland','Ramarama'),
  ('Bombay','Auckland','Bombay'),
  ('Waiheke Island','Auckland','Waiheke Island'),
  ('Blackpool','Auckland','Waiheke Island'),
  ('Oneroa','Auckland','Waiheke Island'),
  ('Onetangi','Auckland','Waiheke Island'),
  ('Ostend','Auckland','Waiheke Island'),
  ('Palm Beach','Auckland','Waiheke Island'),
  ('Rocky Bay','Auckland','Waiheke Island'),
  ('Surfdale','Auckland','Waiheke Island'),
  ('Great Barrier Island','Auckland','Great Barrier Island'),
  ('Claris','Auckland','Great Barrier Island'),
  ('Medlands','Auckland','Great Barrier Island'),
  ('Okiwi','Auckland','Great Barrier Island'),
  ('Okupu','Auckland','Great Barrier Island'),
  ('Port FitzRoy','Auckland','Great Barrier Island'),
  ('Tryphena','Auckland','Great Barrier Island'),
  ('Whangaparapara','Auckland','Great Barrier Island'),
  ('Kawau Island','Auckland','Kawau Island'),
  ('Whangarei','Northland','Whangarei'),
  ('Avenues','Northland','Whangarei'),
  ('Glenbervie','Northland','Whangarei'),
  ('Horahora','Northland','Whangarei'),
  ('Kamo','Northland','Whangarei'),
  ('Kensington','Northland','Whangarei'),
  ('Mairtown','Northland','Whangarei'),
  ('Maunu','Northland','Whangarei'),
  ('Morningside','Northland','Whangarei'),
  ('Onerahi','Northland','Whangarei'),
  ('Otaika','Northland','Whangarei'),
  ('Otangarei','Northland','Whangarei'),
  ('Parua Bay','Northland','Whangarei'),
  ('Raumanga','Northland','Whangarei'),
  ('Regent','Northland','Whangarei'),
  ('Riverside','Northland','Whangarei'),
  ('Sherwood Rise','Northland','Whangarei'),
  ('Springs Flat','Northland','Whangarei'),
  ('Three Mile Bush','Northland','Whangarei'),
  ('Tikipunga','Northland','Whangarei'),
  ('Whau Valley','Northland','Whangarei'),
  ('Woodhill','Northland','Whangarei'),
  ('Kerikeri','Northland','Kerikeri'),
  ('Waipapa','Northland','Waipapa'),
  ('Paihia','Northland','Paihia'),
  ('Waitangi','Northland','Waitangi'),
  ('Haruru','Northland','Haruru'),
  ('Opua','Northland','Opua'),
  ('Russell','Northland','Russell'),
  ('Kawakawa','Northland','Kawakawa'),
  ('Moerewa','Northland','Moerewa'),
  ('Kaikohe','Northland','Kaikohe'),
  ('Ngawha Springs','Northland','Ngawha Springs'),
  ('Okaihau','Northland','Okaihau'),
  ('Ohaeawai','Northland','Ohaeawai'),
  ('Kaeo','Northland','Kaeo'),
  ('Whangaroa','Northland','Whangaroa'),
  ('Totara North','Northland','Totara North'),
  ('Matauri Bay','Northland','Matauri Bay'),
  ('Mangonui','Northland','Mangonui'),
  ('Coopers Beach','Northland','Coopers Beach'),
  ('Cable Bay','Northland','Cable Bay'),
  ('Taipa','Northland','Taipa'),
  ('Hihi','Northland','Hihi'),
  ('Whatuwhiwhi','Northland','Whatuwhiwhi'),
  ('Tokerau Beach','Northland','Tokerau Beach'),
  ('Awanui','Northland','Awanui'),
  ('Kaitaia','Northland','Kaitaia'),
  ('Ahipara','Northland','Ahipara'),
  ('Pukenui','Northland','Pukenui'),
  ('Houhora','Northland','Houhora'),
  ('Ngataki','Northland','Ngataki'),
  ('Te Kao','Northland','Te Kao'),
  ('Herekino','Northland','Herekino'),
  ('Broadwood','Northland','Broadwood'),
  ('Panguru','Northland','Panguru'),
  ('Kohukohu','Northland','Kohukohu'),
  ('Rawene','Northland','Rawene'),
  ('Horeke','Northland','Horeke'),
  ('Opononi','Northland','Opononi'),
  ('Omapere','Northland','Omapere'),
  ('Waimamaku','Northland','Waimamaku'),
  ('Hikurangi','Northland','Hikurangi'),
  ('Whakapara','Northland','Whakapara'),
  ('Towai','Northland','Towai'),
  ('Ngunguru','Northland','Ngunguru'),
  ('Tutukaka','Northland','Tutukaka'),
  ('Matapouri','Northland','Matapouri'),
  ('Whananaki','Northland','Whananaki'),
  ('Oakura','Northland','Oakura'),
  ('Whangarei Heads','Northland','Whangarei Heads'),
  ('McLeod Bay','Northland','McLeod Bay'),
  ('Pataua','Northland','Pataua'),
  ('Portland','Northland','Portland'),
  ('Oakleigh','Northland','Oakleigh'),
  ('Ruakaka','Northland','Ruakaka'),
  ('One Tree Point','Northland','One Tree Point'),
  ('Marsden Point','Northland','Marsden Point'),
  ('Waipu','Northland','Waipu'),
  ('Waipu Cove','Northland','Waipu Cove'),
  ('Langs Beach','Northland','Langs Beach'),
  ('Mangawhai','Northland','Mangawhai'),
  ('Mangawhai Heads','Northland','Mangawhai Heads'),
  ('Kaiwaka','Northland','Kaiwaka'),
  ('Maungaturoto','Northland','Maungaturoto'),
  ('Paparoa','Northland','Paparoa'),
  ('Matakohe','Northland','Matakohe'),
  ('Ruawai','Northland','Ruawai'),
  ('Te Kopuru','Northland','Te Kopuru'),
  ('Dargaville','Northland','Dargaville'),
  ('Baylys Beach','Northland','Baylys Beach'),
  ('Tangowahine','Northland','Tangowahine'),
  ('Kaihu','Northland','Kaihu'),
  ('Tangiteroria','Northland','Tangiteroria'),
  ('Maungakaramea','Northland','Maungakaramea'),
  ('Waiotira','Northland','Waiotira'),
  ('Poroti','Northland','Poroti'),
  ('Titoki','Northland','Titoki'),
  ('Kokopu','Northland','Kokopu'),
  ('Hamilton','Waikato','Hamilton'),
  ('Bader','Waikato','Hamilton'),
  ('Beerescourt','Waikato','Hamilton'),
  ('Burbush','Waikato','Hamilton'),
  ('Chartwell','Waikato','Hamilton'),
  ('Chedworth Park','Waikato','Hamilton'),
  ('Claudelands','Waikato','Hamilton'),
  ('Crawshaw','Waikato','Hamilton'),
  ('Deanwell','Waikato','Hamilton'),
  ('Dinsdale','Waikato','Hamilton'),
  ('Enderley','Waikato','Hamilton'),
  ('Fairfield','Waikato','Hamilton'),
  ('Fairview Downs','Waikato','Hamilton'),
  ('Fitzroy','Waikato','Hamilton'),
  ('Flagstaff','Waikato','Hamilton'),
  ('Forest Lake','Waikato','Hamilton'),
  ('Frankton','Waikato','Hamilton'),
  ('Glenview','Waikato','Hamilton'),
  ('Grandview Heights','Waikato','Hamilton'),
  ('Hamilton Central','Waikato','Hamilton'),
  ('Hamilton East','Waikato','Hamilton'),
  ('Harrowfield','Waikato','Hamilton'),
  ('Hillcrest','Waikato','Hamilton'),
  ('Horsham Downs','Waikato','Hamilton'),
  ('Huntington','Waikato','Hamilton'),
  ('Maeroa','Waikato','Hamilton'),
  ('Melville','Waikato','Hamilton'),
  ('Nawton','Waikato','Hamilton'),
  ('Peacocke','Waikato','Hamilton'),
  ('Pukete','Waikato','Hamilton'),
  ('Queenwood','Waikato','Hamilton'),
  ('Riverlea','Waikato','Hamilton'),
  ('Rototuna','Waikato','Hamilton'),
  ('Rototuna North','Waikato','Hamilton'),
  ('Rotokauri','Waikato','Hamilton'),
  ('Ruakura','Waikato','Hamilton'),
  ('Silverdale','Waikato','Hamilton'),
  ('St Andrews','Waikato','Hamilton'),
  ('Te Rapa','Waikato','Hamilton'),
  ('Temple View','Waikato','Hamilton'),
  ('Western Heights','Waikato','Hamilton'),
  ('Whitiora','Waikato','Hamilton'),
  ('Cambridge','Waikato','Cambridge'),
  ('Karapiro','Waikato','Karapiro'),
  ('Te Awamutu','Waikato','Te Awamutu'),
  ('Kihikihi','Waikato','Kihikihi'),
  ('Pirongia','Waikato','Pirongia'),
  ('Ohaupo','Waikato','Ohaupo'),
  ('Ngahinapouri','Waikato','Ngahinapouri'),
  ('Rukuhia','Waikato','Rukuhia'),
  ('Tamahere','Waikato','Tamahere'),
  ('Matangi','Waikato','Matangi'),
  ('Tauwhare','Waikato','Tauwhare'),
  ('Newstead','Waikato','Newstead'),
  ('Eureka','Waikato','Eureka'),
  ('Gordonton','Waikato','Gordonton'),
  ('Puketaha','Waikato','Puketaha'),
  ('Te Kowhai','Waikato','Te Kowhai'),
  ('Horotiu','Waikato','Horotiu'),
  ('Whatawhata','Waikato','Whatawhata'),
  ('Ngaruawahia','Waikato','Ngaruawahia'),
  ('Taupiri','Waikato','Taupiri'),
  ('Glen Massey','Waikato','Glen Massey'),
  ('Waingaro','Waikato','Waingaro'),
  ('Raglan','Waikato','Raglan'),
  ('Te Uku','Waikato','Te Uku'),
  ('Huntly','Waikato','Huntly'),
  ('Ohinewai','Waikato','Ohinewai'),
  ('Rangiriri','Waikato','Rangiriri'),
  ('Te Kauwhata','Waikato','Te Kauwhata'),
  ('Meremere','Waikato','Meremere'),
  ('Mercer','Waikato','Mercer'),
  ('Pokeno','Waikato','Pokeno'),
  ('Tuakau','Waikato','Tuakau'),
  ('Onewhero','Waikato','Onewhero'),
  ('Port Waikato','Waikato','Port Waikato'),
  ('Pukekawa','Waikato','Pukekawa'),
  ('Morrinsville','Waikato','Morrinsville'),
  ('Tatuanui','Waikato','Tatuanui'),
  ('Waitoa','Waikato','Waitoa'),
  ('Waharoa','Waikato','Waharoa'),
  ('Matamata','Waikato','Matamata'),
  ('Te Poi','Waikato','Te Poi'),
  ('Walton','Waikato','Walton'),
  ('Hinuera','Waikato','Hinuera'),
  ('Te Aroha','Waikato','Te Aroha'),
  ('Manawaru','Waikato','Manawaru'),
  ('Paeroa','Waikato','Paeroa'),
  ('Waikino','Waikato','Waikino'),
  ('Waihi','Waikato','Waihi'),
  ('Whiritoa','Waikato','Whiritoa'),
  ('Ngatea','Waikato','Ngatea'),
  ('Kerepehi','Waikato','Kerepehi'),
  ('Turua','Waikato','Turua'),
  ('Waitakaruru','Waikato','Waitakaruru'),
  ('Kaiaua','Waikato','Kaiaua'),
  ('Miranda','Waikato','Miranda'),
  ('Thames','Waikato','Thames'),
  ('Te Puru','Waikato','Te Puru'),
  ('Tapu','Waikato','Tapu'),
  ('Coromandel','Waikato','Coromandel'),
  ('Kuaotunu','Waikato','Kuaotunu'),
  ('Matarangi','Waikato','Matarangi'),
  ('Whitianga','Waikato','Whitianga'),
  ('Cooks Beach','Waikato','Cooks Beach'),
  ('Hahei','Waikato','Hahei'),
  ('Hot Water Beach','Waikato','Hot Water Beach'),
  ('Coroglen','Waikato','Coroglen'),
  ('Tairua','Waikato','Tairua'),
  ('Pauanui','Waikato','Pauanui'),
  ('Opoutere','Waikato','Opoutere'),
  ('Onemana','Waikato','Onemana'),
  ('Whangamata','Waikato','Whangamata'),
  ('Tirau','Waikato','Tirau'),
  ('Putaruru','Waikato','Putaruru'),
  ('Arapuni','Waikato','Arapuni'),
  ('Lichfield','Waikato','Lichfield'),
  ('Tokoroa','Waikato','Tokoroa'),
  ('Mangakino','Waikato','Mangakino'),
  ('Whakamaru','Waikato','Whakamaru'),
  ('Otorohanga','Waikato','Otorohanga'),
  ('Kawhia','Waikato','Kawhia'),
  ('Te Kuiti','Waikato','Te Kuiti'),
  ('Waitomo Caves','Waikato','Waitomo Caves'),
  ('Piopio','Waikato','Piopio'),
  ('Aria','Waikato','Aria'),
  ('Benneydale','Waikato','Benneydale'),
  ('Marokopa','Waikato','Marokopa'),
  ('Mokau','Waikato','Mokau'),
  ('Awakino','Waikato','Awakino'),
  ('Taupo','Waikato','Taupo'),
  ('Acacia Bay','Waikato','Taupo'),
  ('Hilltop','Waikato','Taupo'),
  ('Nukuhau','Waikato','Taupo'),
  ('Rainbow Point','Waikato','Taupo'),
  ('Richmond Heights','Waikato','Taupo'),
  ('Tauhara','Waikato','Taupo'),
  ('Two Mile Bay','Waikato','Taupo'),
  ('Waipahihi','Waikato','Taupo'),
  ('Wharewaka','Waikato','Taupo'),
  ('Kinloch','Waikato','Kinloch'),
  ('Wairakei','Waikato','Wairakei'),
  ('Waitahanui','Waikato','Waitahanui'),
  ('Motuoapa','Waikato','Motuoapa'),
  ('Turangi','Waikato','Turangi'),
  ('Tokaanu','Waikato','Tokaanu'),
  ('Kuratau','Waikato','Kuratau'),
  ('Omori','Waikato','Omori'),
  ('Pukawa','Waikato','Pukawa'),
  ('Tauranga','Bay of Plenty','Tauranga'),
  ('Tauranga Central','Bay of Plenty','Tauranga'),
  ('Tauranga South','Bay of Plenty','Tauranga'),
  ('The Avenues','Bay of Plenty','Tauranga'),
  ('Judea','Bay of Plenty','Tauranga'),
  ('Otumoetai','Bay of Plenty','Tauranga'),
  ('Matua','Bay of Plenty','Tauranga'),
  ('Bureta','Bay of Plenty','Tauranga'),
  ('Cherrywood','Bay of Plenty','Tauranga'),
  ('Bellevue','Bay of Plenty','Tauranga'),
  ('Brookfield','Bay of Plenty','Tauranga'),
  ('Bethlehem','Bay of Plenty','Tauranga'),
  ('Pillans Point','Bay of Plenty','Tauranga'),
  ('Gate Pa','Bay of Plenty','Tauranga'),
  ('Merivale','Bay of Plenty','Tauranga'),
  ('Greerton','Bay of Plenty','Tauranga'),
  ('Parkvale','Bay of Plenty','Tauranga'),
  ('Pyes Pa','Bay of Plenty','Tauranga'),
  ('Tauriko','Bay of Plenty','Tauranga'),
  ('Ohauiti','Bay of Plenty','Tauranga'),
  ('Hairini','Bay of Plenty','Tauranga'),
  ('Maungatapu','Bay of Plenty','Tauranga'),
  ('Welcome Bay','Bay of Plenty','Tauranga'),
  ('Poike','Bay of Plenty','Tauranga'),
  ('Matapihi','Bay of Plenty','Tauranga'),
  ('Sulphur Point','Bay of Plenty','Tauranga'),
  ('Mount Maunganui','Bay of Plenty','Tauranga'),
  ('Omanu','Bay of Plenty','Tauranga'),
  ('Arataki','Bay of Plenty','Tauranga'),
  ('Bayfair','Bay of Plenty','Tauranga'),
  ('Papamoa','Bay of Plenty','Tauranga'),
  ('Papamoa Beach','Bay of Plenty','Tauranga'),
  ('Palm Beach','Bay of Plenty','Tauranga'),
  ('Te Puke','Bay of Plenty','Te Puke'),
  ('Katikati','Bay of Plenty','Katikati'),
  ('Omokoroa','Bay of Plenty','Omokoroa'),
  ('Waihi Beach','Bay of Plenty','Waihi Beach'),
  ('Athenree','Bay of Plenty','Athenree'),
  ('Bowentown','Bay of Plenty','Bowentown'),
  ('Te Puna','Bay of Plenty','Te Puna'),
  ('Minden','Bay of Plenty','Minden'),
  ('Whakamarama','Bay of Plenty','Whakamarama'),
  ('Aongatete','Bay of Plenty','Aongatete'),
  ('Kauri Point','Bay of Plenty','Kauri Point'),
  ('Tanners Point','Bay of Plenty','Tanners Point'),
  ('Matakana Island','Bay of Plenty','Matakana Island'),
  ('Oropi','Bay of Plenty','Oropi'),
  ('Kaimai','Bay of Plenty','Kaimai'),
  ('Paengaroa','Bay of Plenty','Paengaroa'),
  ('Pongakawa','Bay of Plenty','Pongakawa'),
  ('Maketu','Bay of Plenty','Maketu'),
  ('Pukehina','Bay of Plenty','Pukehina'),
  ('Otamarakau','Bay of Plenty','Otamarakau'),
  ('Rotorua','Bay of Plenty','Rotorua'),
  ('Rotorua Central','Bay of Plenty','Rotorua'),
  ('Glenholme','Bay of Plenty','Rotorua'),
  ('Springfield','Bay of Plenty','Rotorua'),
  ('Fenton Park','Bay of Plenty','Rotorua'),
  ('Victoria','Bay of Plenty','Rotorua'),
  ('Utuhina','Bay of Plenty','Rotorua'),
  ('Kuirau','Bay of Plenty','Rotorua'),
  ('Mangakakahi','Bay of Plenty','Rotorua'),
  ('Western Heights','Bay of Plenty','Rotorua'),
  ('Selwyn Heights','Bay of Plenty','Rotorua'),
  ('Fordlands','Bay of Plenty','Rotorua'),
  ('Pomare','Bay of Plenty','Rotorua'),
  ('Sunnybrook','Bay of Plenty','Rotorua'),
  ('Hillcrest','Bay of Plenty','Rotorua'),
  ('Ohinemutu','Bay of Plenty','Rotorua'),
  ('Koutu','Bay of Plenty','Rotorua'),
  ('Kawaha Point','Bay of Plenty','Rotorua'),
  ('Fairy Springs','Bay of Plenty','Rotorua'),
  ('Ngongotaha','Bay of Plenty','Rotorua'),
  ('Ngongotaha Valley','Bay of Plenty','Rotorua'),
  ('Whakarewarewa','Bay of Plenty','Rotorua'),
  ('Ngapuna','Bay of Plenty','Rotorua'),
  ('Owhata','Bay of Plenty','Rotorua'),
  ('Lynmore','Bay of Plenty','Rotorua'),
  ('Holdens Bay','Bay of Plenty','Rotorua'),
  ('Hannahs Bay','Bay of Plenty','Rotorua'),
  ('Tihiotonga','Bay of Plenty','Rotorua'),
  ('Hamurana','Bay of Plenty','Hamurana'),
  ('Mamaku','Bay of Plenty','Mamaku'),
  ('Kaharoa','Bay of Plenty','Kaharoa'),
  ('Okere Falls','Bay of Plenty','Okere Falls'),
  ('Mourea','Bay of Plenty','Mourea'),
  ('Rotoiti','Bay of Plenty','Rotoiti'),
  ('Rotoehu','Bay of Plenty','Rotoehu'),
  ('Tikitere','Bay of Plenty','Tikitere'),
  ('Lake Tarawera','Bay of Plenty','Lake Tarawera'),
  ('Lake Okareka','Bay of Plenty','Lake Okareka'),
  ('Rerewhakaaitu','Bay of Plenty','Rerewhakaaitu'),
  ('Reporoa','Bay of Plenty','Reporoa'),
  ('Ngakuru','Bay of Plenty','Ngakuru'),
  ('Waikite Valley','Bay of Plenty','Waikite Valley'),
  ('Horohoro','Bay of Plenty','Horohoro'),
  ('Whakatane','Bay of Plenty','Whakatane'),
  ('Whakatane Central','Bay of Plenty','Whakatane'),
  ('Awatapu','Bay of Plenty','Whakatane'),
  ('Coastlands','Bay of Plenty','Whakatane'),
  ('Piripai','Bay of Plenty','Whakatane'),
  ('Otarawairere','Bay of Plenty','Whakatane'),
  ('Mokorua','Bay of Plenty','Whakatane'),
  ('Ohope','Bay of Plenty','Ohope'),
  ('Edgecumbe','Bay of Plenty','Edgecumbe'),
  ('Te Teko','Bay of Plenty','Te Teko'),
  ('Otakiri','Bay of Plenty','Otakiri'),
  ('Awakeri','Bay of Plenty','Awakeri'),
  ('Thornton','Bay of Plenty','Thornton'),
  ('Poroporo','Bay of Plenty','Poroporo'),
  ('Taneatua','Bay of Plenty','Taneatua'),
  ('Waimana','Bay of Plenty','Waimana'),
  ('Ruatoki','Bay of Plenty','Ruatoki'),
  ('Matata','Bay of Plenty','Matata'),
  ('Pikowai','Bay of Plenty','Pikowai'),
  ('Manawahe','Bay of Plenty','Manawahe'),
  ('Murupara','Bay of Plenty','Murupara'),
  ('Galatea','Bay of Plenty','Galatea'),
  ('Waiohau','Bay of Plenty','Waiohau'),
  ('Te Mahoe','Bay of Plenty','Te Mahoe'),
  ('Minginui','Bay of Plenty','Minginui'),
  ('Te Whaiti','Bay of Plenty','Te Whaiti'),
  ('Ruatahuna','Bay of Plenty','Ruatahuna'),
  ('Kaingaroa','Bay of Plenty','Kaingaroa'),
  ('Kawerau','Bay of Plenty','Kawerau'),
  ('Opotiki','Bay of Plenty','Opotiki'),
  ('Waiotahe','Bay of Plenty','Waiotahe'),
  ('Ohiwa','Bay of Plenty','Ohiwa'),
  ('Omarumutu','Bay of Plenty','Omarumutu'),
  ('Torere','Bay of Plenty','Torere'),
  ('Hawai','Bay of Plenty','Hawai'),
  ('Omaio','Bay of Plenty','Omaio'),
  ('Te Kaha','Bay of Plenty','Te Kaha'),
  ('Whanarua Bay','Bay of Plenty','Whanarua Bay'),
  ('Raukokore','Bay of Plenty','Raukokore'),
  ('Waihau Bay','Bay of Plenty','Waihau Bay'),
  ('Cape Runaway','Bay of Plenty','Cape Runaway'),
  ('Gisborne','Gisborne','Gisborne'),
  ('Gisborne Central','Gisborne','Gisborne'),
  ('Whataupoko','Gisborne','Gisborne'),
  ('Mangapapa','Gisborne','Gisborne'),
  ('Te Hapara','Gisborne','Gisborne'),
  ('Elgin','Gisborne','Gisborne'),
  ('Awapuni','Gisborne','Gisborne'),
  ('Riverdale','Gisborne','Gisborne'),
  ('Lytton West','Gisborne','Gisborne'),
  ('Kaiti','Gisborne','Gisborne'),
  ('Outer Kaiti','Gisborne','Gisborne'),
  ('Tamarau','Gisborne','Gisborne'),
  ('Makaraka','Gisborne','Gisborne'),
  ('Matawhero','Gisborne','Gisborne'),
  ('Wainui','Gisborne','Gisborne'),
  ('Okitu','Gisborne','Gisborne'),
  ('Wainui Beach','Gisborne','Wainui Beach'),
  ('Makorori','Gisborne','Makorori'),
  ('Tatapouri','Gisborne','Tatapouri'),
  ('Whangara','Gisborne','Whangara'),
  ('Manutuke','Gisborne','Manutuke'),
  ('Muriwai','Gisborne','Muriwai'),
  ('Patutahi','Gisborne','Patutahi'),
  ('Ormond','Gisborne','Ormond'),
  ('Ngatapa','Gisborne','Ngatapa'),
  ('Rere','Gisborne','Rere'),
  ('Waerengaokuri','Gisborne','Waerengaokuri'),
  ('Tiniroto','Gisborne','Tiniroto'),
  ('Te Karaka','Gisborne','Te Karaka'),
  ('Whatatutu','Gisborne','Whatatutu'),
  ('Matawai','Gisborne','Matawai'),
  ('Motu','Gisborne','Motu'),
  ('Tolaga Bay','Gisborne','Tolaga Bay'),
  ('Tokomaru Bay','Gisborne','Tokomaru Bay'),
  ('Waipiro Bay','Gisborne','Waipiro Bay'),
  ('Te Puia Springs','Gisborne','Te Puia Springs'),
  ('Ruatoria','Gisborne','Ruatoria'),
  ('Tikitiki','Gisborne','Tikitiki'),
  ('Rangitukia','Gisborne','Rangitukia'),
  ('Te Araroa','Gisborne','Te Araroa'),
  ('Hicks Bay','Gisborne','Hicks Bay'),
  ('Potaka','Gisborne','Potaka'),
  ('Napier','Hawke''s Bay','Napier'),
  ('Napier Central','Hawke''s Bay','Napier'),
  ('Napier South','Hawke''s Bay','Napier'),
  ('Bluff Hill','Hawke''s Bay','Napier'),
  ('Hospital Hill','Hawke''s Bay','Napier'),
  ('Ahuriri','Hawke''s Bay','Napier'),
  ('Westshore','Hawke''s Bay','Napier'),
  ('Bay View','Hawke''s Bay','Napier'),
  ('Poraiti','Hawke''s Bay','Napier'),
  ('Marewa','Hawke''s Bay','Napier'),
  ('Onekawa','Hawke''s Bay','Napier'),
  ('Pirimai','Hawke''s Bay','Napier'),
  ('Tamatea','Hawke''s Bay','Napier'),
  ('Greenmeadows','Hawke''s Bay','Napier'),
  ('Taradale','Hawke''s Bay','Napier'),
  ('Maraenui','Hawke''s Bay','Napier'),
  ('Meeanee','Hawke''s Bay','Napier'),
  ('Awatoto','Hawke''s Bay','Napier'),
  ('Jervoistown','Hawke''s Bay','Napier'),
  ('Te Awa','Hawke''s Bay','Napier'),
  ('Hastings','Hawke''s Bay','Hastings'),
  ('Hastings Central','Hawke''s Bay','Hastings'),
  ('Mayfair','Hawke''s Bay','Hastings'),
  ('Raureka','Hawke''s Bay','Hastings'),
  ('Akina','Hawke''s Bay','Hastings'),
  ('Parkvale','Hawke''s Bay','Hastings'),
  ('Mahora','Hawke''s Bay','Hastings'),
  ('Frimley','Hawke''s Bay','Hastings'),
  ('Camberley','Hawke''s Bay','Hastings'),
  ('St Leonards','Hawke''s Bay','Hastings'),
  ('Tomoana','Hawke''s Bay','Hastings'),
  ('Havelock North','Hawke''s Bay','Hastings'),
  ('Flaxmere','Hawke''s Bay','Hastings'),
  ('Clive','Hawke''s Bay','Clive'),
  ('Whakatu','Hawke''s Bay','Whakatu'),
  ('Haumoana','Hawke''s Bay','Haumoana'),
  ('Te Awanga','Hawke''s Bay','Te Awanga'),
  ('Waimarama','Hawke''s Bay','Waimarama'),
  ('Pakipaki','Hawke''s Bay','Pakipaki'),
  ('Bridge Pa','Hawke''s Bay','Bridge Pa'),
  ('Twyford','Hawke''s Bay','Twyford'),
  ('Fernhill','Hawke''s Bay','Fernhill'),
  ('Maraekakaho','Hawke''s Bay','Maraekakaho'),
  ('Puketapu','Hawke''s Bay','Puketapu'),
  ('Rissington','Hawke''s Bay','Rissington'),
  ('Patoka','Hawke''s Bay','Patoka'),
  ('Puketitiri','Hawke''s Bay','Puketitiri'),
  ('Eskdale','Hawke''s Bay','Eskdale'),
  ('Tangoio','Hawke''s Bay','Tangoio'),
  ('Tutira','Hawke''s Bay','Tutira'),
  ('Te Pohue','Hawke''s Bay','Te Pohue'),
  ('Putorino','Hawke''s Bay','Putorino'),
  ('Mohaka','Hawke''s Bay','Mohaka'),
  ('Raupunga','Hawke''s Bay','Raupunga'),
  ('Wairoa','Hawke''s Bay','Wairoa'),
  ('Frasertown','Hawke''s Bay','Frasertown'),
  ('Tuai','Hawke''s Bay','Tuai'),
  ('Waikaremoana','Hawke''s Bay','Waikaremoana'),
  ('Ruakituri','Hawke''s Bay','Ruakituri'),
  ('Whakaki','Hawke''s Bay','Whakaki'),
  ('Nuhaka','Hawke''s Bay','Nuhaka'),
  ('Morere','Hawke''s Bay','Morere'),
  ('Mahia','Hawke''s Bay','Mahia'),
  ('Mahia Beach','Hawke''s Bay','Mahia Beach'),
  ('Waipawa','Hawke''s Bay','Waipawa'),
  ('Waipukurau','Hawke''s Bay','Waipukurau'),
  ('Otane','Hawke''s Bay','Otane'),
  ('Tikokino','Hawke''s Bay','Tikokino'),
  ('Ongaonga','Hawke''s Bay','Ongaonga'),
  ('Takapau','Hawke''s Bay','Takapau'),
  ('Elsthorpe','Hawke''s Bay','Elsthorpe'),
  ('Porangahau','Hawke''s Bay','Porangahau'),
  ('Kairakau Beach','Hawke''s Bay','Kairakau Beach'),
  ('Hatuma','Hawke''s Bay','Hatuma'),
  ('New Plymouth','Taranaki','New Plymouth'),
  ('New Plymouth Central','Taranaki','New Plymouth'),
  ('Strandon','Taranaki','New Plymouth'),
  ('Fitzroy','Taranaki','New Plymouth'),
  ('Glen Avon','Taranaki','New Plymouth'),
  ('Merrilands','Taranaki','New Plymouth'),
  ('Highlands Park','Taranaki','New Plymouth'),
  ('Welbourn','Taranaki','New Plymouth'),
  ('Vogeltown','Taranaki','New Plymouth'),
  ('Frankleigh Park','Taranaki','New Plymouth'),
  ('Hurdon','Taranaki','New Plymouth'),
  ('Westown','Taranaki','New Plymouth'),
  ('Marfell','Taranaki','New Plymouth'),
  ('Spotswood','Taranaki','New Plymouth'),
  ('Moturoa','Taranaki','New Plymouth'),
  ('Lynmouth','Taranaki','New Plymouth'),
  ('Blagdon','Taranaki','New Plymouth'),
  ('Brooklands','Taranaki','New Plymouth'),
  ('Hillsborough','Taranaki','New Plymouth'),
  ('Mangorei','Taranaki','New Plymouth'),
  ('Waiwhakaiho','Taranaki','New Plymouth'),
  ('Bell Block','Taranaki','New Plymouth'),
  ('Ferndale','Taranaki','New Plymouth'),
  ('Waitara','Taranaki','Waitara'),
  ('Inglewood','Taranaki','Inglewood'),
  ('Oakura','Taranaki','Oakura'),
  ('Okato','Taranaki','Okato'),
  ('Urenui','Taranaki','Urenui'),
  ('Onaero','Taranaki','Onaero'),
  ('Tikorangi','Taranaki','Tikorangi'),
  ('Motunui','Taranaki','Motunui'),
  ('Lepperton','Taranaki','Lepperton'),
  ('Egmont Village','Taranaki','Egmont Village'),
  ('Uruti','Taranaki','Uruti'),
  ('Tongaporutu','Taranaki','Tongaporutu'),
  ('Omata','Taranaki','Omata'),
  ('Warea','Taranaki','Warea'),
  ('Pungarehu','Taranaki','Pungarehu'),
  ('Parihaka','Taranaki','Parihaka'),
  ('Rahotu','Taranaki','Rahotu'),
  ('Oaonui','Taranaki','Oaonui'),
  ('Opunake','Taranaki','Opunake'),
  ('Otakeho','Taranaki','Otakeho'),
  ('Manaia','Taranaki','Manaia'),
  ('Kaponga','Taranaki','Kaponga'),
  ('Eltham','Taranaki','Eltham'),
  ('Stratford','Taranaki','Stratford'),
  ('Midhirst','Taranaki','Midhirst'),
  ('Tariki','Taranaki','Tariki'),
  ('Toko','Taranaki','Toko'),
  ('Douglas','Taranaki','Douglas'),
  ('Te Wera','Taranaki','Te Wera'),
  ('Whangamomona','Taranaki','Whangamomona'),
  ('Hawera','Taranaki','Hawera'),
  ('Normanby','Taranaki','Normanby'),
  ('Okaiawa','Taranaki','Okaiawa'),
  ('Matapu','Taranaki','Matapu'),
  ('Kakaramea','Taranaki','Kakaramea'),
  ('Manutahi','Taranaki','Manutahi'),
  ('Patea','Taranaki','Patea'),
  ('Whenuakura','Taranaki','Whenuakura'),
  ('Waverley','Taranaki','Waverley'),
  ('Waitotara','Taranaki','Waitotara'),
  ('Palmerston North','Manawatu-Whanganui','Palmerston North'),
  ('Palmerston North Central','Manawatu-Whanganui','Palmerston North'),
  ('West End','Manawatu-Whanganui','Palmerston North'),
  ('Terrace End','Manawatu-Whanganui','Palmerston North'),
  ('Hokowhitu','Manawatu-Whanganui','Palmerston North'),
  ('Awapuni','Manawatu-Whanganui','Palmerston North'),
  ('Takaro','Manawatu-Whanganui','Palmerston North'),
  ('Highbury','Manawatu-Whanganui','Palmerston North'),
  ('Cloverlea','Manawatu-Whanganui','Palmerston North'),
  ('Milson','Manawatu-Whanganui','Palmerston North'),
  ('Kelvin Grove','Manawatu-Whanganui','Palmerston North'),
  ('Roslyn','Manawatu-Whanganui','Palmerston North'),
  ('Westbrook','Manawatu-Whanganui','Palmerston North'),
  ('Aokautere','Manawatu-Whanganui','Palmerston North'),
  ('Fitzherbert','Manawatu-Whanganui','Palmerston North'),
  ('Summerhill','Manawatu-Whanganui','Palmerston North'),
  ('Whakarongo','Manawatu-Whanganui','Palmerston North'),
  ('Whanganui','Manawatu-Whanganui','Whanganui'),
  ('Whanganui Central','Manawatu-Whanganui','Whanganui'),
  ('Whanganui East','Manawatu-Whanganui','Whanganui'),
  ('Aramoho','Manawatu-Whanganui','Whanganui'),
  ('Castlecliff','Manawatu-Whanganui','Whanganui'),
  ('Gonville','Manawatu-Whanganui','Whanganui'),
  ('Springvale','Manawatu-Whanganui','Whanganui'),
  ('St Johns Hill','Manawatu-Whanganui','Whanganui'),
  ('Durie Hill','Manawatu-Whanganui','Whanganui'),
  ('Bastia Hill','Manawatu-Whanganui','Whanganui'),
  ('College Estate','Manawatu-Whanganui','Whanganui'),
  ('Tawhero','Manawatu-Whanganui','Whanganui'),
  ('Otamatea','Manawatu-Whanganui','Whanganui'),
  ('Putiki','Manawatu-Whanganui','Whanganui'),
  ('Westmere','Manawatu-Whanganui','Whanganui'),
  ('Kaierau','Manawatu-Whanganui','Whanganui'),
  ('Wembley Park','Manawatu-Whanganui','Whanganui'),
  ('Feilding','Manawatu-Whanganui','Feilding'),
  ('Levin','Manawatu-Whanganui','Levin'),
  ('Marton','Manawatu-Whanganui','Marton'),
  ('Dannevirke','Manawatu-Whanganui','Dannevirke'),
  ('Taumarunui','Manawatu-Whanganui','Taumarunui'),
  ('Foxton','Manawatu-Whanganui','Foxton'),
  ('Foxton Beach','Manawatu-Whanganui','Foxton Beach'),
  ('Bulls','Manawatu-Whanganui','Bulls'),
  ('Taihape','Manawatu-Whanganui','Taihape'),
  ('Ohakune','Manawatu-Whanganui','Ohakune'),
  ('Raetihi','Manawatu-Whanganui','Raetihi'),
  ('Waiouru','Manawatu-Whanganui','Waiouru'),
  ('National Park','Manawatu-Whanganui','National Park'),
  ('Pahiatua','Manawatu-Whanganui','Pahiatua'),
  ('Woodville','Manawatu-Whanganui','Woodville'),
  ('Eketahuna','Manawatu-Whanganui','Eketahuna'),
  ('Norsewood','Manawatu-Whanganui','Norsewood'),
  ('Ormondville','Manawatu-Whanganui','Ormondville'),
  ('Shannon','Manawatu-Whanganui','Shannon'),
  ('Tokomaru','Manawatu-Whanganui','Tokomaru'),
  ('Ashhurst','Manawatu-Whanganui','Ashhurst'),
  ('Sanson','Manawatu-Whanganui','Sanson'),
  ('Rongotea','Manawatu-Whanganui','Rongotea'),
  ('Halcombe','Manawatu-Whanganui','Halcombe'),
  ('Kimbolton','Manawatu-Whanganui','Kimbolton'),
  ('Cheltenham','Manawatu-Whanganui','Cheltenham'),
  ('Colyton','Manawatu-Whanganui','Colyton'),
  ('Awahuri','Manawatu-Whanganui','Awahuri'),
  ('Apiti','Manawatu-Whanganui','Apiti'),
  ('Pohangina','Manawatu-Whanganui','Pohangina'),
  ('Himatangi Beach','Manawatu-Whanganui','Himatangi Beach'),
  ('Tangimoana','Manawatu-Whanganui','Tangimoana'),
  ('Waitarere Beach','Manawatu-Whanganui','Waitarere Beach'),
  ('Hokio Beach','Manawatu-Whanganui','Hokio Beach'),
  ('Waikawa Beach','Manawatu-Whanganui','Waikawa Beach'),
  ('Manakau','Manawatu-Whanganui','Manakau'),
  ('Ohau','Manawatu-Whanganui','Ohau'),
  ('Kuku','Manawatu-Whanganui','Kuku'),
  ('Opiki','Manawatu-Whanganui','Opiki'),
  ('Hunterville','Manawatu-Whanganui','Hunterville'),
  ('Mangaweka','Manawatu-Whanganui','Mangaweka'),
  ('Utiku','Manawatu-Whanganui','Utiku'),
  ('Ohingaiti','Manawatu-Whanganui','Ohingaiti'),
  ('Turakina','Manawatu-Whanganui','Turakina'),
  ('Ratana','Manawatu-Whanganui','Ratana'),
  ('Koitiata','Manawatu-Whanganui','Koitiata'),
  ('Kai Iwi','Manawatu-Whanganui','Kai Iwi'),
  ('Maxwell','Manawatu-Whanganui','Maxwell'),
  ('Fordell','Manawatu-Whanganui','Fordell'),
  ('Upokongaro','Manawatu-Whanganui','Upokongaro'),
  ('Brunswick','Manawatu-Whanganui','Brunswick'),
  ('Mowhanau','Manawatu-Whanganui','Mowhanau'),
  ('Whangaehu','Manawatu-Whanganui','Whangaehu'),
  ('Jerusalem','Manawatu-Whanganui','Jerusalem'),
  ('Ranana','Manawatu-Whanganui','Ranana'),
  ('Koriniti','Manawatu-Whanganui','Koriniti'),
  ('Pipiriki','Manawatu-Whanganui','Pipiriki'),
  ('Owhango','Manawatu-Whanganui','Owhango'),
  ('Manunui','Manawatu-Whanganui','Manunui'),
  ('Kakahi','Manawatu-Whanganui','Kakahi'),
  ('Piriaka','Manawatu-Whanganui','Piriaka'),
  ('Ongarue','Manawatu-Whanganui','Ongarue'),
  ('Waimiha','Manawatu-Whanganui','Waimiha'),
  ('Ohura','Manawatu-Whanganui','Ohura'),
  ('Matiere','Manawatu-Whanganui','Matiere'),
  ('Raurimu','Manawatu-Whanganui','Raurimu'),
  ('Horopito','Manawatu-Whanganui','Horopito'),
  ('Erua','Manawatu-Whanganui','Erua'),
  ('Rangataua','Manawatu-Whanganui','Rangataua'),
  ('Whakapapa Village','Manawatu-Whanganui','Whakapapa Village'),
  ('Pongaroa','Manawatu-Whanganui','Pongaroa'),
  ('Weber','Manawatu-Whanganui','Weber'),
  ('Akitio','Manawatu-Whanganui','Akitio'),
  ('Herbertville','Manawatu-Whanganui','Herbertville'),
  ('Alfredton','Manawatu-Whanganui','Alfredton'),
  ('Mangatainoka','Manawatu-Whanganui','Mangatainoka'),
  ('Longburn','Manawatu-Whanganui','Longburn'),
  ('Linton','Manawatu-Whanganui','Linton'),
  ('Bunnythorpe','Manawatu-Whanganui','Bunnythorpe'),
  ('Wellington City','Wellington','Wellington City'),
  ('Wellington Central','Wellington','Wellington City'),
  ('Te Aro','Wellington','Wellington City'),
  ('Thorndon','Wellington','Wellington City'),
  ('Pipitea','Wellington','Wellington City'),
  ('Mount Victoria','Wellington','Wellington City'),
  ('Mount Cook','Wellington','Wellington City'),
  ('Aro Valley','Wellington','Wellington City'),
  ('Kelburn','Wellington','Wellington City'),
  ('Northland','Wellington','Wellington City'),
  ('Karori','Wellington','Wellington City'),
  ('Wilton','Wellington','Wellington City'),
  ('Wadestown','Wellington','Wellington City'),
  ('Highbury','Wellington','Wellington City'),
  ('Brooklyn','Wellington','Wellington City'),
  ('Vogeltown','Wellington','Wellington City'),
  ('Mornington','Wellington','Wellington City'),
  ('Kingston','Wellington','Wellington City'),
  ('Happy Valley','Wellington','Wellington City'),
  ('Berhampore','Wellington','Wellington City'),
  ('Newtown','Wellington','Wellington City'),
  ('Melrose','Wellington','Wellington City'),
  ('Island Bay','Wellington','Wellington City'),
  ('Owhiro Bay','Wellington','Wellington City'),
  ('Houghton Bay','Wellington','Wellington City'),
  ('Southgate','Wellington','Wellington City'),
  ('Lyall Bay','Wellington','Wellington City'),
  ('Rongotai','Wellington','Wellington City'),
  ('Kilbirnie','Wellington','Wellington City'),
  ('Hataitai','Wellington','Wellington City'),
  ('Roseneath','Wellington','Wellington City'),
  ('Oriental Bay','Wellington','Wellington City'),
  ('Evans Bay','Wellington','Wellington City'),
  ('Maupuia','Wellington','Wellington City'),
  ('Miramar','Wellington','Wellington City'),
  ('Strathmore Park','Wellington','Wellington City'),
  ('Seatoun','Wellington','Wellington City'),
  ('Breaker Bay','Wellington','Wellington City'),
  ('Moa Point','Wellington','Wellington City'),
  ('Worser Bay','Wellington','Wellington City'),
  ('Karaka Bays','Wellington','Wellington City'),
  ('Ngaio','Wellington','Wellington City'),
  ('Khandallah','Wellington','Wellington City'),
  ('Crofton Downs','Wellington','Wellington City'),
  ('Broadmeadows','Wellington','Wellington City'),
  ('Kaiwharawhara','Wellington','Wellington City'),
  ('Ngauranga','Wellington','Wellington City'),
  ('Johnsonville','Wellington','Wellington City'),
  ('Newlands','Wellington','Wellington City'),
  ('Paparangi','Wellington','Wellington City'),
  ('Woodridge','Wellington','Wellington City'),
  ('Grenada Village','Wellington','Wellington City'),
  ('Grenada North','Wellington','Wellington City'),
  ('Churton Park','Wellington','Wellington City'),
  ('Glenside','Wellington','Wellington City'),
  ('Horokiwi','Wellington','Wellington City'),
  ('Tawa','Wellington','Wellington City'),
  ('Linden','Wellington','Wellington City'),
  ('Redwood','Wellington','Wellington City'),
  ('Takapu Valley','Wellington','Wellington City'),
  ('Makara','Wellington','Wellington City'),
  ('Makara Beach','Wellington','Wellington City'),
  ('Ohariu','Wellington','Wellington City'),
  ('Lower Hutt','Wellington','Lower Hutt'),
  ('Hutt Central','Wellington','Lower Hutt'),
  ('Petone','Wellington','Lower Hutt'),
  ('Alicetown','Wellington','Lower Hutt'),
  ('Melling','Wellington','Lower Hutt'),
  ('Belmont','Wellington','Lower Hutt'),
  ('Kelson','Wellington','Lower Hutt'),
  ('Maungaraki','Wellington','Lower Hutt'),
  ('Normandale','Wellington','Lower Hutt'),
  ('Tirohanga','Wellington','Lower Hutt'),
  ('Korokoro','Wellington','Lower Hutt'),
  ('Harbour View','Wellington','Lower Hutt'),
  ('Boulcott','Wellington','Lower Hutt'),
  ('Epuni','Wellington','Lower Hutt'),
  ('Waterloo','Wellington','Lower Hutt'),
  ('Woburn','Wellington','Lower Hutt'),
  ('Moera','Wellington','Lower Hutt'),
  ('Waiwhetu','Wellington','Lower Hutt'),
  ('Gracefield','Wellington','Lower Hutt'),
  ('Seaview','Wellington','Lower Hutt'),
  ('Naenae','Wellington','Lower Hutt'),
  ('Avalon','Wellington','Lower Hutt'),
  ('Taita','Wellington','Lower Hutt'),
  ('Fairfield','Wellington','Lower Hutt'),
  ('Stokes Valley','Wellington','Lower Hutt'),
  ('Manor Park','Wellington','Lower Hutt'),
  ('Haywards','Wellington','Lower Hutt'),
  ('Wainuiomata','Wellington','Lower Hutt'),
  ('Arakura','Wellington','Lower Hutt'),
  ('Homedale','Wellington','Lower Hutt'),
  ('Parkway','Wellington','Lower Hutt'),
  ('Eastbourne','Wellington','Lower Hutt'),
  ('Days Bay','Wellington','Lower Hutt'),
  ('Lowry Bay','Wellington','Lower Hutt'),
  ('York Bay','Wellington','Lower Hutt'),
  ('Mahina Bay','Wellington','Lower Hutt'),
  ('Point Howard','Wellington','Lower Hutt'),
  ('Muritai','Wellington','Lower Hutt'),
  ('Sunshine Bay','Wellington','Lower Hutt'),
  ('Upper Hutt','Wellington','Upper Hutt'),
  ('Upper Hutt Central','Wellington','Upper Hutt'),
  ('Trentham','Wellington','Upper Hutt'),
  ('Heretaunga','Wellington','Upper Hutt'),
  ('Silverstream','Wellington','Upper Hutt'),
  ('Pinehaven','Wellington','Upper Hutt'),
  ('Wallaceville','Wellington','Upper Hutt'),
  ('Elderslea','Wellington','Upper Hutt'),
  ('Ebdentown','Wellington','Upper Hutt'),
  ('Clouston Park','Wellington','Upper Hutt'),
  ('Totara Park','Wellington','Upper Hutt'),
  ('Maoribank','Wellington','Upper Hutt'),
  ('Birchville','Wellington','Upper Hutt'),
  ('Brown Owl','Wellington','Upper Hutt'),
  ('Timberlea','Wellington','Upper Hutt'),
  ('Te Marua','Wellington','Upper Hutt'),
  ('Kaitoke','Wellington','Upper Hutt'),
  ('Akatarawa','Wellington','Upper Hutt'),
  ('Maymorn','Wellington','Upper Hutt'),
  ('Riverstone Terraces','Wellington','Upper Hutt'),
  ('Whitemans Valley','Wellington','Upper Hutt'),
  ('Blue Mountains','Wellington','Upper Hutt'),
  ('Emerald Hill','Wellington','Upper Hutt'),
  ('Mount Marua','Wellington','Upper Hutt'),
  ('Porirua','Wellington','Porirua'),
  ('Porirua Central','Wellington','Porirua'),
  ('Porirua East','Wellington','Porirua'),
  ('Cannons Creek','Wellington','Porirua'),
  ('Waitangirua','Wellington','Porirua'),
  ('Ranui Heights','Wellington','Porirua'),
  ('Ascot Park','Wellington','Porirua'),
  ('Elsdon','Wellington','Porirua'),
  ('Takapuwahia','Wellington','Porirua'),
  ('Titahi Bay','Wellington','Porirua'),
  ('Kenepuru','Wellington','Porirua'),
  ('Aotea','Wellington','Porirua'),
  ('Whitby','Wellington','Porirua'),
  ('Papakowhai','Wellington','Porirua'),
  ('Paremata','Wellington','Porirua'),
  ('Camborne','Wellington','Porirua'),
  ('Mana','Wellington','Porirua'),
  ('Plimmerton','Wellington','Porirua'),
  ('Karehana Bay','Wellington','Porirua'),
  ('Pukerua Bay','Wellington','Porirua'),
  ('Hongoeka','Wellington','Porirua'),
  ('Pauatahanui','Wellington','Porirua'),
  ('Judgeford','Wellington','Porirua'),
  ('Paraparaumu','Wellington','Paraparaumu'),
  ('Paraparaumu Beach','Wellington','Paraparaumu'),
  ('Raumati Beach','Wellington','Paraparaumu'),
  ('Raumati South','Wellington','Paraparaumu'),
  ('Otaihanga','Wellington','Paraparaumu'),
  ('Kena Kena','Wellington','Paraparaumu'),
  ('Waikanae','Wellington','Waikanae'),
  ('Waikanae Beach','Wellington','Waikanae'),
  ('Waikanae East','Wellington','Waikanae'),
  ('Otaki','Wellington','Otaki'),
  ('Otaki Beach','Wellington','Otaki'),
  ('Otaki Railway','Wellington','Otaki'),
  ('Paekakariki','Wellington','Paekakariki'),
  ('Te Horo','Wellington','Te Horo'),
  ('Peka Peka','Wellington','Peka Peka'),
  ('Masterton','Wellington','Masterton'),
  ('Masterton Central','Wellington','Masterton'),
  ('Lansdowne','Wellington','Masterton'),
  ('Solway','Wellington','Masterton'),
  ('Kuripuni','Wellington','Masterton'),
  ('Upper Plain','Wellington','Masterton'),
  ('Douglas Park','Wellington','Masterton'),
  ('Carterton','Wellington','Carterton'),
  ('Greytown','Wellington','Greytown'),
  ('Featherston','Wellington','Featherston'),
  ('Martinborough','Wellington','Martinborough'),
  ('Riversdale Beach','Wellington','Riversdale Beach'),
  ('Castlepoint','Wellington','Castlepoint'),
  ('Tinui','Wellington','Tinui'),
  ('Mauriceville','Wellington','Mauriceville'),
  ('Opaki','Wellington','Opaki'),
  ('Gladstone','Wellington','Gladstone'),
  ('Ngawi','Wellington','Ngawi'),
  ('Lake Ferry','Wellington','Lake Ferry'),
  ('Pirinoa','Wellington','Pirinoa'),
  ('Blenheim','Marlborough','Blenheim'),
  ('Blenheim Central','Marlborough','Blenheim'),
  ('Springlands','Marlborough','Blenheim'),
  ('Redwoodtown','Marlborough','Blenheim'),
  ('Witherlea','Marlborough','Blenheim'),
  ('Mayfield','Marlborough','Blenheim'),
  ('Riversdale','Marlborough','Blenheim'),
  ('Islington','Marlborough','Blenheim'),
  ('Burleigh','Marlborough','Blenheim'),
  ('Whitney Street','Marlborough','Blenheim'),
  ('Omaka','Marlborough','Blenheim'),
  ('Picton','Marlborough','Picton'),
  ('Picton Central','Marlborough','Picton'),
  ('Waikawa','Marlborough','Picton'),
  ('Renwick','Marlborough','Renwick'),
  ('Havelock','Marlborough','Havelock'),
  ('Seddon','Marlborough','Seddon'),
  ('Ward','Marlborough','Ward'),
  ('Rai Valley','Marlborough','Rai Valley'),
  ('Spring Creek','Marlborough','Spring Creek'),
  ('Grovetown','Marlborough','Grovetown'),
  ('Tuamarina','Marlborough','Tuamarina'),
  ('Rapaura','Marlborough','Rapaura'),
  ('Rarangi','Marlborough','Rarangi'),
  ('Fairhall','Marlborough','Fairhall'),
  ('Wairau Valley','Marlborough','Wairau Valley'),
  ('Riverlands','Marlborough','Riverlands'),
  ('Woodbourne','Marlborough','Woodbourne'),
  ('Koromiko','Marlborough','Koromiko'),
  ('Linkwater','Marlborough','Linkwater'),
  ('Anakiwa','Marlborough','Anakiwa'),
  ('Canvastown','Marlborough','Canvastown'),
  ('Okiwi Bay','Marlborough','Okiwi Bay'),
  ('French Pass','Marlborough','French Pass'),
  ('Portage','Marlborough','Portage'),
  ('Ngakuta Bay','Marlborough','Ngakuta Bay'),
  ('Te Mahia','Marlborough','Te Mahia'),
  ('Elaine Bay','Marlborough','Elaine Bay'),
  ('Nelson','Nelson','Nelson'),
  ('Nelson Central','Nelson','Nelson'),
  ('The Wood','Nelson','Nelson'),
  ('The Brook','Nelson','Nelson'),
  ('Britannia Heights','Nelson','Nelson'),
  ('Nelson South','Nelson','Nelson'),
  ('Toi Toi','Nelson','Nelson'),
  ('Washington Valley','Nelson','Nelson'),
  ('Port Nelson','Nelson','Nelson'),
  ('Tahunanui','Nelson','Nelson'),
  ('Bishopdale','Nelson','Nelson'),
  ('Enner Glynn','Nelson','Nelson'),
  ('Ngawhatu','Nelson','Nelson'),
  ('Stoke','Nelson','Nelson'),
  ('Wakatu','Nelson','Nelson'),
  ('Annesbrook','Nelson','Nelson'),
  ('Monaco','Nelson','Nelson'),
  ('Nayland','Nelson','Nelson'),
  ('Atawhai','Nelson','Nelson'),
  ('Marybank','Nelson','Nelson'),
  ('Wakapuaka','Nelson','Nelson'),
  ('Maitai Valley','Nelson','Nelson'),
  ('Beachville','Nelson','Nelson'),
  ('Isel Park','Nelson','Nelson'),
  ('Ranzau','Nelson','Nelson'),
  ('Hira','Nelson','Hira'),
  ('Cable Bay','Nelson','Cable Bay'),
  ('Glenduan','Nelson','Glenduan'),
  ('Todds Valley','Nelson','Todds Valley'),
  ('Richmond','Tasman','Richmond'),
  ('Motueka','Tasman','Motueka'),
  ('Takaka','Tasman','Takaka'),
  ('Brightwater','Tasman','Brightwater'),
  ('Wakefield','Tasman','Wakefield'),
  ('Mapua','Tasman','Mapua'),
  ('Murchison','Tasman','Murchison'),
  ('Tapawera','Tasman','Tapawera'),
  ('Collingwood','Tasman','Collingwood'),
  ('Riwaka','Tasman','Riwaka'),
  ('Kaiteriteri','Tasman','Kaiteriteri'),
  ('Marahau','Tasman','Marahau'),
  ('Ngatimoti','Tasman','Ngatimoti'),
  ('Upper Moutere','Tasman','Upper Moutere'),
  ('Lower Moutere','Tasman','Lower Moutere'),
  ('Tasman','Tasman','Tasman'),
  ('Ruby Bay','Tasman','Ruby Bay'),
  ('Hope','Tasman','Hope'),
  ('Appleby','Tasman','Appleby'),
  ('Redwood Valley','Tasman','Redwood Valley'),
  ('Wai-iti','Tasman','Wai-iti'),
  ('Foxhill','Tasman','Foxhill'),
  ('Belgrove','Tasman','Belgrove'),
  ('Motupiko','Tasman','Motupiko'),
  ('Korere','Tasman','Korere'),
  ('Golden Downs','Tasman','Golden Downs'),
  ('Stanley Brook','Tasman','Stanley Brook'),
  ('Dovedale','Tasman','Dovedale'),
  ('St Arnaud','Tasman','St Arnaud'),
  ('Owen River','Tasman','Owen River'),
  ('Glenhope','Tasman','Glenhope'),
  ('Pohara','Tasman','Pohara'),
  ('Ligar Bay','Tasman','Ligar Bay'),
  ('Tata Beach','Tasman','Tata Beach'),
  ('Patons Rock','Tasman','Patons Rock'),
  ('Onekaka','Tasman','Onekaka'),
  ('Puponga','Tasman','Puponga'),
  ('Bainham','Tasman','Bainham'),
  ('Tarakohe','Tasman','Tarakohe'),
  ('Westport','West Coast','Westport'),
  ('Carters Beach','West Coast','Carters Beach'),
  ('Cape Foulwind','West Coast','Cape Foulwind'),
  ('Charleston','West Coast','Charleston'),
  ('Waimangaroa','West Coast','Waimangaroa'),
  ('Granity','West Coast','Granity'),
  ('Ngakawau','West Coast','Ngakawau'),
  ('Hector','West Coast','Hector'),
  ('Seddonville','West Coast','Seddonville'),
  ('Mokihinui','West Coast','Mokihinui'),
  ('Little Wanganui','West Coast','Little Wanganui'),
  ('Karamea','West Coast','Karamea'),
  ('Inangahua Junction','West Coast','Inangahua Junction'),
  ('Reefton','West Coast','Reefton'),
  ('Springs Junction','West Coast','Springs Junction'),
  ('Maruia','West Coast','Maruia'),
  ('Ikamatua','West Coast','Ikamatua'),
  ('Ahaura','West Coast','Ahaura'),
  ('Nelson Creek','West Coast','Nelson Creek'),
  ('Totara Flat','West Coast','Totara Flat'),
  ('Blackball','West Coast','Blackball'),
  ('Runanga','West Coast','Runanga'),
  ('Rapahoe','West Coast','Rapahoe'),
  ('Barrytown','West Coast','Barrytown'),
  ('Punakaiki','West Coast','Punakaiki'),
  ('Greymouth','West Coast','Greymouth'),
  ('Blaketown','West Coast','Greymouth'),
  ('Cobden','West Coast','Greymouth'),
  ('Karoro','West Coast','Greymouth'),
  ('Boddytown','West Coast','Greymouth'),
  ('Marsden','West Coast','Greymouth'),
  ('Gladstone','West Coast','Greymouth'),
  ('South Beach','West Coast','Greymouth'),
  ('Paroa','West Coast','Greymouth'),
  ('Kaiata','West Coast','Greymouth'),
  ('Dobson','West Coast','Dobson'),
  ('Taylorville','West Coast','Taylorville'),
  ('Stillwater','West Coast','Stillwater'),
  ('Moana','West Coast','Moana'),
  ('Kumara','West Coast','Kumara'),
  ('Kumara Junction','West Coast','Kumara Junction'),
  ('Otira','West Coast','Otira'),
  ('Hokitika','West Coast','Hokitika'),
  ('Arahura','West Coast','Arahura'),
  ('Ross','West Coast','Ross'),
  ('Ruatapu','West Coast','Ruatapu'),
  ('Hari Hari','West Coast','Hari Hari'),
  ('Whataroa','West Coast','Whataroa'),
  ('Franz Josef','West Coast','Franz Josef'),
  ('Fox Glacier','West Coast','Fox Glacier'),
  ('Bruce Bay','West Coast','Bruce Bay'),
  ('Haast','West Coast','Haast'),
  ('Jackson Bay','West Coast','Jackson Bay'),
  ('Okuru','West Coast','Okuru'),
  ('Oamaru','Otago','Oamaru'),
  ('Awamoa','Otago','Oamaru'),
  ('Glen Warren','Otago','Oamaru'),
  ('Holmes Hill','Otago','Oamaru'),
  ('Redcastle','Otago','Oamaru'),
  ('South Hill','Otago','Oamaru'),
  ('Weston','Otago','Oamaru'),
  ('Kakanui','Otago','Kakanui'),
  ('Maheno','Otago','Maheno'),
  ('Enfield','Otago','Enfield'),
  ('Ngapara','Otago','Ngapara'),
  ('Tokarahi','Otago','Tokarahi'),
  ('Duntroon','Otago','Duntroon'),
  ('Kurow','Otago','Kurow'),
  ('Otematata','Otago','Otematata'),
  ('Omarama','Otago','Omarama'),
  ('Georgetown','Otago','Georgetown'),
  ('Herbert','Otago','Herbert'),
  ('Waianakarua','Otago','Waianakarua'),
  ('Hampden','Otago','Hampden'),
  ('Moeraki','Otago','Moeraki'),
  ('Palmerston','Otago','Palmerston'),
  ('Dunback','Otago','Dunback'),
  ('Macraes Flat','Otago','Macraes Flat'),
  ('Waikouaiti','Otago','Waikouaiti'),
  ('Karitane','Otago','Karitane'),
  ('Seacliff','Otago','Seacliff'),
  ('Warrington','Otago','Warrington'),
  ('Waitati','Otago','Waitati'),
  ('Purakaunui','Otago','Purakaunui'),
  ('Aramoana','Otago','Aramoana'),
  ('Dunedin','Otago','Dunedin'),
  ('Abbotsford','Otago','Dunedin'),
  ('Andersons Bay','Otago','Dunedin'),
  ('Balaclava','Otago','Dunedin'),
  ('Belleknowes','Otago','Dunedin'),
  ('Broad Bay','Otago','Dunedin'),
  ('Brockville','Otago','Dunedin'),
  ('Burnside','Otago','Dunedin'),
  ('Calton Hill','Otago','Dunedin'),
  ('Caversham','Otago','Dunedin'),
  ('City Rise','Otago','Dunedin'),
  ('Company Bay','Otago','Dunedin'),
  ('Concord','Otago','Dunedin'),
  ('Corstorphine','Otago','Dunedin'),
  ('Dalmore','Otago','Dunedin'),
  ('Dunedin Central','Otago','Dunedin'),
  ('Fairfield','Otago','Dunedin'),
  ('Forbury','Otago','Dunedin'),
  ('Glenleith','Otago','Dunedin'),
  ('Green Island','Otago','Dunedin'),
  ('Halfway Bush','Otago','Dunedin'),
  ('Helensburgh','Otago','Dunedin'),
  ('Kaikorai','Otago','Dunedin'),
  ('Kenmure','Otago','Dunedin'),
  ('Kew','Otago','Dunedin'),
  ('Leith Valley','Otago','Dunedin'),
  ('Liberton','Otago','Dunedin'),
  ('Lookout Point','Otago','Dunedin'),
  ('Macandrew Bay','Otago','Dunedin'),
  ('Maia','Otago','Dunedin'),
  ('Maori Hill','Otago','Dunedin'),
  ('Maryhill','Otago','Dunedin'),
  ('Mornington','Otago','Dunedin'),
  ('Mosgiel','Otago','Dunedin'),
  ('Musselburgh','Otago','Dunedin'),
  ('Normanby','Otago','Dunedin'),
  ('North Dunedin','Otago','Dunedin'),
  ('North East Valley','Otago','Dunedin'),
  ('Ocean Grove','Otago','Dunedin'),
  ('Ocean View','Otago','Dunedin'),
  ('Opoho','Otago','Dunedin'),
  ('Pine Hill','Otago','Dunedin'),
  ('Port Chalmers','Otago','Dunedin'),
  ('Portobello','Otago','Dunedin'),
  ('Ravensbourne','Otago','Dunedin'),
  ('Roslyn','Otago','Dunedin'),
  ('Sawyers Bay','Otago','Dunedin'),
  ('Shiel Hill','Otago','Dunedin'),
  ('South Dunedin','Otago','Dunedin'),
  ('St Clair','Otago','Dunedin'),
  ('St Kilda','Otago','Dunedin'),
  ('St Leonards','Otago','Dunedin'),
  ('Sunnyvale','Otago','Dunedin'),
  ('Tainui','Otago','Dunedin'),
  ('Vauxhall','Otago','Dunedin'),
  ('Wakari','Otago','Dunedin'),
  ('Waldronville','Otago','Dunedin'),
  ('Waverley','Otago','Dunedin'),
  ('Woodhaugh','Otago','Dunedin'),
  ('Careys Bay','Otago','Careys Bay'),
  ('Outram','Otago','Outram'),
  ('East Taieri','Otago','East Taieri'),
  ('Wingatui','Otago','Wingatui'),
  ('Allanton','Otago','Allanton'),
  ('Momona','Otago','Momona'),
  ('Henley','Otago','Henley'),
  ('Brighton','Otago','Brighton'),
  ('Taieri Mouth','Otago','Taieri Mouth'),
  ('Waihola','Otago','Waihola'),
  ('Middlemarch','Otago','Middlemarch'),
  ('Hyde','Otago','Hyde'),
  ('Sutton','Otago','Sutton'),
  ('Milton','Otago','Milton'),
  ('Waitahuna','Otago','Waitahuna'),
  ('Lawrence','Otago','Lawrence'),
  ('Beaumont','Otago','Beaumont'),
  ('Balclutha','Otago','Balclutha'),
  ('Stirling','Otago','Stirling'),
  ('Kaitangata','Otago','Kaitangata'),
  ('Clydevale','Otago','Clydevale'),
  ('Owaka','Otago','Owaka'),
  ('Pounawea','Otago','Pounawea'),
  ('Kaka Point','Otago','Kaka Point'),
  ('Papatowai','Otago','Papatowai'),
  ('Clinton','Otago','Clinton'),
  ('Waiwera South','Otago','Waiwera South'),
  ('Tapanui','Otago','Tapanui'),
  ('Heriot','Otago','Heriot'),
  ('Ettrick','Otago','Ettrick'),
  ('Millers Flat','Otago','Millers Flat'),
  ('Roxburgh','Otago','Roxburgh'),
  ('Alexandra','Otago','Alexandra'),
  ('Clyde','Otago','Clyde'),
  ('Earnscleugh','Otago','Earnscleugh'),
  ('Chatto Creek','Otago','Chatto Creek'),
  ('Omakau','Otago','Omakau'),
  ('Ophir','Otago','Ophir'),
  ('Lauder','Otago','Lauder'),
  ('Becks','Otago','Becks'),
  ('St Bathans','Otago','St Bathans'),
  ('Oturehua','Otago','Oturehua'),
  ('Wedderburn','Otago','Wedderburn'),
  ('Naseby','Otago','Naseby'),
  ('Ranfurly','Otago','Ranfurly'),
  ('Patearoa','Otago','Patearoa'),
  ('Waipiata','Otago','Waipiata'),
  ('Kyeburn','Otago','Kyeburn'),
  ('Poolburn','Otago','Poolburn'),
  ('Cromwell','Otago','Cromwell'),
  ('Bannockburn','Otago','Bannockburn'),
  ('Lowburn','Otago','Lowburn'),
  ('Pisa Moorings','Otago','Pisa Moorings'),
  ('Tarras','Otago','Tarras'),
  ('Luggate','Otago','Luggate'),
  ('Wanaka','Otago','Wanaka'),
  ('Albert Town','Otago','Albert Town'),
  ('Hawea Flat','Otago','Hawea Flat'),
  ('Lake Hawea','Otago','Lake Hawea'),
  ('Makarora','Otago','Makarora'),
  ('Cardrona','Otago','Cardrona'),
  ('Arrowtown','Otago','Arrowtown'),
  ('Queenstown','Otago','Queenstown'),
  ('Arthurs Point','Otago','Queenstown'),
  ('Fernhill','Otago','Queenstown'),
  ('Frankton','Otago','Queenstown'),
  ('Hanleys Farm','Otago','Queenstown'),
  ('Jacks Point','Otago','Queenstown'),
  ('Kelvin Heights','Otago','Queenstown'),
  ('Lake Hayes','Otago','Queenstown'),
  ('Lake Hayes Estate','Otago','Queenstown'),
  ('Quail Rise','Otago','Queenstown'),
  ('Queenstown Hill','Otago','Queenstown'),
  ('Shotover Country','Otago','Queenstown'),
  ('Sunshine Bay','Otago','Queenstown'),
  ('Gibbston','Otago','Gibbston'),
  ('Glenorchy','Otago','Glenorchy'),
  ('Kinloch','Otago','Kinloch'),
  ('Kingston','Otago','Kingston'),
  ('Invercargill','Southland','Invercargill'),
  ('Appleby','Southland','Invercargill'),
  ('Avenal','Southland','Invercargill'),
  ('Clifton','Southland','Invercargill'),
  ('Georgetown','Southland','Invercargill'),
  ('Gladstone','Southland','Invercargill'),
  ('Glengarry','Southland','Invercargill'),
  ('Grasmere','Southland','Invercargill'),
  ('Hargest','Southland','Invercargill'),
  ('Hawthorndale','Southland','Invercargill'),
  ('Heidelberg','Southland','Invercargill'),
  ('Invercargill Central','Southland','Invercargill'),
  ('Kew','Southland','Invercargill'),
  ('Kingswell','Southland','Invercargill'),
  ('Myross Bush','Southland','Invercargill'),
  ('Newfield','Southland','Invercargill'),
  ('Otatara','Southland','Invercargill'),
  ('Prestonville','Southland','Invercargill'),
  ('Richmond','Southland','Invercargill'),
  ('Rosedale','Southland','Invercargill'),
  ('Strathern','Southland','Invercargill'),
  ('Tisbury','Southland','Invercargill'),
  ('Waikiwi','Southland','Invercargill'),
  ('Waverley','Southland','Invercargill'),
  ('Windsor','Southland','Invercargill'),
  ('Woodend','Southland','Invercargill'),
  ('Bluff','Southland','Bluff'),
  ('Kennington','Southland','Kennington'),
  ('Makarewa','Southland','Makarewa'),
  ('Lorneville','Southland','Lorneville'),
  ('Ryal Bush','Southland','Ryal Bush'),
  ('Wallacetown','Southland','Wallacetown'),
  ('Waianiwa','Southland','Waianiwa'),
  ('Winton','Southland','Winton'),
  ('Limehills','Southland','Limehills'),
  ('Centre Bush','Southland','Centre Bush'),
  ('Dipton','Southland','Dipton'),
  ('Lumsden','Southland','Lumsden'),
  ('Mossburn','Southland','Mossburn'),
  ('Athol','Southland','Athol'),
  ('Garston','Southland','Garston'),
  ('Balfour','Southland','Balfour'),
  ('Riversdale','Southland','Riversdale'),
  ('Waikaia','Southland','Waikaia'),
  ('Waikaka','Southland','Waikaka'),
  ('Mandeville','Southland','Mandeville'),
  ('Gore','Southland','Gore'),
  ('East Gore','Southland','Gore'),
  ('Mataura','Southland','Mataura'),
  ('Pukerau','Southland','Pukerau'),
  ('Edendale','Southland','Edendale'),
  ('Wyndham','Southland','Wyndham'),
  ('Woodlands','Southland','Woodlands'),
  ('Dacre','Southland','Dacre'),
  ('Mokotua','Southland','Mokotua'),
  ('Gorge Road','Southland','Gorge Road'),
  ('Tokanui','Southland','Tokanui'),
  ('Fortrose','Southland','Fortrose'),
  ('Waikawa','Southland','Waikawa'),
  ('Curio Bay','Southland','Curio Bay'),
  ('Otautau','Southland','Otautau'),
  ('Nightcaps','Southland','Nightcaps'),
  ('Ohai','Southland','Ohai'),
  ('Drummond','Southland','Drummond'),
  ('Browns','Southland','Browns'),
  ('Thornbury','Southland','Thornbury'),
  ('Riverton','Southland','Riverton'),
  ('Colac Bay','Southland','Colac Bay'),
  ('Orepuki','Southland','Orepuki'),
  ('Tuatapere','Southland','Tuatapere'),
  ('Clifden','Southland','Clifden'),
  ('Blackmount','Southland','Blackmount'),
  ('Manapouri','Southland','Manapouri'),
  ('Te Anau','Southland','Te Anau'),
  ('Milford Sound','Southland','Milford Sound'),
  ('Oban','Southland','Oban')
on conflict (name, region) do nothing;
